#Filter based on language tag

PREFIX schema: <http://schema.org/>

SELECT ?name
FROM <http://worldcat.org/entity/work/id/67201841>
WHERE {
?s schema:name ?name .
FILTER(langMatches(lang(?name), ”en"))
}